### ISSUE TITLE
Missing cfg.yaml

### ISSUE THREAD

**Issue by AIMads** [radekd91/emoca#31]
Hey I have compiled most of the program now faced issues with ffmpeg but fixed it, but it seems there is a missing cfg.yaml file?

Traceback (most recent call last):
  File "demos/test_emoca_on_video.py", line 111, in <module>
    main()
  File "demos/test_emoca_on_video.py", line 75, in main
    emoca, conf = load_model(path_to_models, model_name, mode)
  File "/home/mil/Desktop/emoca/gdl_apps/EMOCA/utils/load.py", line 167, in load_model
    with open(Path(run_path) / "cfg.yaml", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mil/Desktop/emoca/assets/EMOCA/models/EMOCA/cfg.yaml'

**Comment by radekd91** [comment]
Have you used the `download_assets.sh` script to download the trained model? Has it downloaded successfully?
