### ISSUE TITLE
The video file '/assets/data/EMOCA_test_example_data/videos/82-25-854x480_affwild2.mp4' is corrupted. Skipping it.

### ISSUE THREAD

**Issue by swerizwan** [radekd91/emoca#75]
I don't know why I am getting that error, The path is correct and video is also fine. 

The video file '/assets/data/EMOCA_test_example_data/videos/82-25-854x480_affwild2.mp4' is corrupted. Skipping it.

Processing dataset
  0%|                                                                                               | 0/1 [00:00<?, ?it/s]/assets/data/EMOCA_test_example_data/videos/82-25-854x480_affwild2.mp4
The video file '/assets/data/EMOCA_test_example_data/videos/82-25-854x480_affwild2.mp4' is corrupted. Skipping it.
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 55.22it/s]
Traceback (most recent call last):
  File "gdl_apps/EMOCA/demos/test_emoca_on_video.py", line 172, in <module>
    main()
  File "gdl_apps/EMOCA/demos/test_emoca_on_video.py", line 167, in main
    reconstruct_video(args)
  File "gdl_apps/EMOCA/demos/test_emoca_on_video.py", line 62, in reconstruct_video
    dm.prepare_data()
  File "/home/abbas/anaconda3/envs/emoo36/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/abbas/emoca/gdl/datasets/FaceVideoDataModule.py", line 3192, in prepare_data
    self._gather_data(exist_ok=True)
  File "/home/abbas/emoca/gdl/datasets/FaceVideoDataModule.py", line 3214, in _gather_data
    self._gather_video_metadata()
  File "/home/abbas/emoca/gdl/datasets/FaceVideoDataModule.py", line 1570, in _gather_video_metadata
    del self.annotation_list[vi]
IndexError: list assignment index out of range

**Comment by ImistroI** [comment]
I have the same issue, did you fix it?

**Comment by ImistroI** [comment]
FYI: I fixed the problem.
my ffmpeg was corrupted. When I tried to call FFmpe

**Comment by ImistroI** [comment]
FYI: I fixed the problem.
my ffmpeg was corrupted. Whenever I tried to call ffmpeg from the terminal I got this message: "ffprobe: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory"
I have solved it by downloading from here my binary: https://github.com/cisco/openh264/releases/tag/v2.1.1 then extract it and renaming it to libopenh264.so.5 and then moving it to "${CONDA_PREFIX}/lib". 
Also I add in the emoca/gdl/utils/FaceVideoDataModule.py the import ffmpeg (not sure if needed but on my system works).
Also the test video from there didn't work but my own input video works (don't know why)

**Comment by swerizwan** [comment]
Yeah, I have also fixed the issue, in my case I think there was the wrong path to the video.

**Comment by zizimars** [comment]
I faced the same issue. But after running on my own video it finally works

**Comment by wang5d** [comment]
I faced the same issue，I changed my own video and still reported this error，Do you know how to fix this
